### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by dylankmoore** [nss-evening-cohort-24/FE-mentorship-program#16]
Each mentor on our app will be associated with a category that they specialize in.

 # User Story
 As an authenticated user, I will see a list of potential mentors and a dropdown menu of the different categories that will sort the mentors based on their associated categories.

 # Acceptance Criteria
When I, the user, click on the mentors page, I will see all of the mentors as well as a dropdown menu of the different categories. If I would like to filter the mentors based on a specific category, I will select that from the dropdown and I can then see the available mentors for that section. This will enable me to navigate the page easier to suit my needs.

 # Dependecies
#2 #7 We need to have our navbar & routing working to navigate to the mentors page.
#4 We need to have our mentors page created
#12 We need to have our mentor cards
#5 We need our file & folder structure to be able to code on the necessary components
#6 We need to ensure our API calls are functional so that we can get our mentors and our categories

 # Dev Notes
We will need to create a dropdown menu with the categories and a function to filter through the mentors.

**Comment by cnfairall** [comment]
see branch cf-filter-cat
was not able to debug in time for deadline
