### ISSUE TITLE
Planning: Initial Setup

### ISSUE THREAD

**Issue by dylankmoore** [nss-evening-cohort-24/FE-mentorship-program#3]
For every project, good planning is required to get a good idea for how the app will function and to understand all of the necessary components & how they work together.

 # Dev Notes
- [Create ERD](https://lucid.app/lucidchart/c77f60ca-5efe-4ece-86a8-d14b1a06a0e6/edit?beaconFlowId=09FAB2CA1F45567A&invitationId=inv_d1e63fa5-7167-4b97-a2db-54ca8ca74ead&referringApp=slack&page=0_0#)
- [Create Flowchart](https://www.figma.com/file/QVKLwZoimYlJyrSJTI4mn9/Untitled?type=whiteboard&node-id=0-1&t=iZkWj91KloIwOBPg-0)
- Discuss between team members what is needed

**Comment by cnfairall** [comment]
https://www.figma.com/file/ijqNETxi8pzegsJaCBDr2U/Mentorship?type=design&node-id=1%3A21&mode=design&t=xVi4a9cpapQ60QcH-1
wireframe

**Comment by cnfairall** [comment]
![image](https://github.com/nss-evening-cohort-24/FE-mentorship-program/assets/101303134/fc88fe1e-a5e3-4c30-83ff-a8d198c793f0)
flow chart

**Comment by cnfairall** [comment]
![image](https://github.com/nss-evening-cohort-24/FE-mentorship-program/assets/101303134/b02b5ba8-6e63-44e3-88e0-5b47b0ebcf76)
ERD
